WebLanches/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('loja.urls')),
]

loja/urls.py
from django.conf.urls import url
from . import views
from django.dispatch import receiver

urlpatterns = [
    url(r'^$', views.home, name = 'home'),
    url(r'^entrar/$', views.login_page, name = 'login'),
    url(r'^sair$', views.sair, name = 'sair'),
    url(r'^cadastrar/$', views.cad_page, name = 'cadastrar'),

    url(r'^cardapio/(?P<tipo>[a-z]*)/$', views.produto_tipo, name = 'produto_tipo'),
    url(r'^add_pedido/(?P<id_produto>[a-zA-Z0-9\s]*)/$', views.add_pedido, name = 'add_pedido'),
    url(r'^cadastrar_produto/$', views.cad_produto, name = 'cadastrar_produto'),
    url(r'^deleta_produto/(?P<id_nome>[a-zA-Z0-9\s]*)/$', views.deleta_produto, name = 'deleta_produto'),


    url(r'^fazer_pedido/$', views.fazer_pedido, name = 'fazer_pedido'),
    url(r'^pedidos/$', views.pedidos_usuario, name = 'pedidos_usuario'),
    url(r'^pedido/(?P<id_pedido>[0-9]+)/itens/$', views.itens_pedido, name = 'itens_pedido'),
    url(r'^alter_status/(?P<id_pedido>[0-9]+)/$', views.alter_status, name = 'alter_status'),
    url(r'^concluir_pedido/(?P<id_pedido>[0-9]+)/$', views.concluir_pedido, name = 'concluir_pedido'),
    url(r'^modificar_qtd_item/(?P<id_item>[0-9]+)/(?P<id_pedido>[0-9]+)/$', views.modificar_qtd_item, name = 'modificar_qtd_item'),
    url(r'^cancelar_pedido/(?P<id_pedido>[0-9]+)/$', views.cancelar_pedido, name = 'cancelar_pedido'),

    url(r'^gerar_pdf/(?P<id_pedido>[0-9]+)/$',views.ver_pdf,name = 'ver_pdf'),
    url(r'^buscar/$', views.buscar, name = 'buscar'),
    url(r'^pedidos-gerenciamento/$', views.all_pedidos, name = 'all_pedidos'),
    url(r'^editar_perfil/$', views.editar_perfil, name = 'editar_perfil'),
]

loja/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import post_save
from PIL import Image

class Usuario(User):
	telefone = models.CharField(max_length = 20)
	cpf = models.CharField(max_length = 20)
	endereco = models.CharField(max_length = 250)
	cep = models.CharField(max_length = 8)

	def save(self,*args,**kwargs):
		self.set_password(self.password)
		User.save(self)


class Produto(models.Model):
	nome = models.CharField(
		max_length = 250,
		primary_key = True
	)
	preco = models.FloatField()
	descricao = models.TextField(blank = True)
	
	imagem = models.ImageField(upload_to = 'loja/static/product_images')

	em_Falta = models.BooleanField()

	PRODUTOS =  (('hamburguer',u'Hambuguer'),
			('bebida',u'Bebida'),
			('pastel',u'Pastel'),
			('pizzas', u'Pizzas'))


	categoria = models.CharField(
		max_length = 10,
		choices = PRODUTOS,
		default = PRODUTOS[0]
	)

	def __str__(self):
		return self.nome

class Item(models.Model):
	id_produto = models.ForeignKey(
		'Produto',
		on_delete = models.CASCADE,
		default = 0,
	)
	id_pedido = models.ForeignKey(
		'Pedido',
		on_delete = models.CASCADE,
		default = 0,
	)

	quantidade = models.IntegerField(default = 0)

	ativo = models.BooleanField(default = True)

	def get_produto():
		produto = Produto.objects.filter()

	@classmethod
	def total(self, id_pedido):
		itens = Item.objects.filter(id_pedido = id_pedido)
		value = 0.0
		for item in itens:
			 produto = Produto.objects.get(nome = item.id_produto)
			 value += (produto.preco*item.quantidade)
		return value

	def addQuantidade(self, quantidade):
		self.quantidade += quantidade

class Pedido(models.Model):
	usuario = models.ForeignKey('auth.User')

	data_do_pedido = models.DateTimeField(default = timezone.now)

	# Em Andamento quando ainda esta na fase de insercao
	# Concluido quando o cliente cncluir suas escolhas
	# Finalizado quando o atendente concluir a producao
	# Em Entrega quando esta a caminho do solicitante
	# Encerrado foi entregue e encerrado
	ESTADO_PEDIDO = (('em_andamento', 'Em Andamento'),
					('concluido', 'Concluido'),
					('finalizado', 'Finalizado'),
					('em_entrega', 'Em Entrega'),
					('encerrado', 'Encerrado'))


	estado_do_pedido = models.CharField(
		max_length = 12,
		choices = ESTADO_PEDIDO,
		default = ESTADO_PEDIDO[0][0])


	def __str__(self):
		return '%s %d' % (self.usuario, self.pk)

	def save(self, force_insert=False, force_update=False):
		self.data_do_pedido = timezone.now()
		super(Pedido, self).save(force_insert, force_update)


# SIGNAL
@receiver(post_save, sender = Pedido)
def create_info(sender, instance, created, **kwargs):
    print ('O Pedido foi salvo')


post_save.connect(create_info, sender = Pedido)

loja/forms.py
# -*- coding=utf-8 -*-
from django import forms
from django.core.exceptions import ValidationError
from .models import Usuario, Pedido, Produto


class FormCadastro(forms.Form):
	nome = forms.CharField(
		widget = forms.TextInput(
			attrs={'autofocus': 'autofocus', 'required': 'required'}),
		max_length = 40)
	email = forms.EmailField(
		widget = forms.TextInput(
			attrs={'required': 'required'}))
	senha = forms.CharField(
		widget = forms.PasswordInput(
			attrs={'required' : 'required', 'onchange' : 'validarTamSenha(senha)'}))
	csenha  = forms.CharField(
		widget = forms.PasswordInput(
			attrs={'required' : 'required' , 'onchange' : 'validarSenha(senha, csenha)'}))
	endereco = forms.CharField(
		widget = forms.TextInput(
			attrs={'required': 'required'}))
	username = forms.CharField(
		widget = forms.TextInput(
			attrs={'required': 'required'}),
		max_length = 40)
	cpf = forms.CharField(
		widget = forms.TextInput(
			attrs={'required': 'required'}))
	telefone = forms.CharField(
		widget = forms.TextInput(
			attrs = {'required': 'required'}))
	cep = forms.CharField(
		widget = forms.TextInput(
			attrs={'required': 'required'}))

	class Meta:
		model = Usuario
		exclude = ['csenha']
		fields = ['nome', 'email', 'senha', 'username', 'telefone', 'cpf', 'endereco', 'cep']

	def clean_usuario(self):
		usuario_novo = self.cleaned_data['username']
		if User.objects.get_by_natural_key(username = usuario_novo) != None:
			raise forms.ValidationError(u'Usuário já existe!')
		else:
			return self.cleaned_data['username']

class FormProduto(forms.Form):
	nome = forms.CharField(
		widget = forms.TextInput(
			attrs={'autofocus': 'autofocus', 'required': 'required'}),
		max_length = 40)

	preco = forms.FloatField(
		widget = forms.TextInput(
			attrs={'required': 'required'}))

	descricao = forms.CharField(
		widget = forms.TextInput(
			attrs={'required' : 'required'}))
	imagem = forms.ImageField(required = False)	

	em_Falta = forms.BooleanField(required=False)

	categoria =  forms.ChoiceField(choices = Produto.PRODUTOS)


class FormLogin(forms.Form):
	usuario = forms.CharField(
		max_length = 40)
	senha = forms.CharField(
		widget = forms.PasswordInput)


class FormStatus(forms.Form):
	status = forms.ChoiceField(choices = Pedido.ESTADO_PEDIDO)

loja/controllers.py
from .models import Usuario, Pedido, Item, Produto
from django.contrib.auth import authenticate, login, logout
from django.db import models
from .forms import FormLogin, FormCadastro
from django.db import IntegrityError
from django.contrib import messages
from django.shortcuts import render, redirect
#contem as operacoes de usuario

class ControllerUsuario:

    def cadastrar(self, request, form):
    	form = FormCadastro(request.POST)

    	if form.is_valid():
            try:
               	usuario = form.cleaned_data['username']
                email = form.cleaned_data['email']
                telefone = form.cleaned_data['telefone']
                nome = form.cleaned_data['nome']
                endereco = form.cleaned_data['endereco']
                senha = form.cleaned_data['senha']
                csenha = form.cleaned_data['csenha']
                cpf = form.cleaned_data['cpf']
                cep = form.cleaned_data['cep']

                user = Usuario()
                user.password =  senha
                user.email = email
                user.telefone = telefone
                user.endereco = endereco
                user.first_name = nome
                user.cpf = cpf
                user.username = usuario
                user.cep = cep
                Usuario.save(user)

            except IntegrityError:
                return False
            else:
                return True
        #return False # Ta com um erro FDP que nao reconhece

    def logar(self, request, form):
    	if form.is_valid():
       		usuario = form.cleaned_data['usuario']
       		senha = form.cleaned_data['senha']
       		user = authenticate(username = usuario, password = senha)
        	if user is not None:
	        	login(request, user)
	        	return True
	        return False


    def sair(self, request):
        logout(request)

    def editar_usuario(self, request, form):
        form = FormCadastro(request.POST)
        if form.is_valid():
            try:
                usuario = form.cleaned_data['username']
                email = form.cleaned_data['email']
                telefone = form.cleaned_data['telefone']
                nome = form.cleaned_data['nome']
                endereco = form.cleaned_data['endereco']
                senha = form.cleaned_data['senha']
                csenha = form.cleaned_data['csenha']
                cpf = form.cleaned_data['cpf']
                cep = form.cleaned_data['cep']

                user = Usuario.objects.get(username=request.user.username)
                user.password = senha
                user.email = email
                user.telefone = telefone
                user.endereco = endereco
                user.first_name = nome
                user.cpf = cpf
                user.cep = cep
                user.save()

            except IntegrityError:
                return False
            else:
                return True

loja/views.py
# -*- coding: utf-8 -*-
from .models import Usuario, Produto, Pedido, Item
from .forms import FormLogin, FormCadastro, FormStatus, FormProduto
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .controllers import ControllerUsuario
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from .report import write_to_pdf

def home(request):
	return redirect(produto_tipo, tipo = 'todos')

def login_page(request):
	if request.user.is_authenticated():
		return redirect(home)

	if request.method == 'POST':
		form = FormLogin(request.POST)
		controller =  ControllerUsuario()
		if controller.logar(request, form):
			return redirect(home)
	else:
		form = FormLogin()

	return render(request,'loja/login/login.html', {'form': form})

def cad_page(request):
	if request.method == 'POST':
		form = FormCadastro(request.POST)
		controller = ControllerUsuario()
		if controller.cadastrar(request, form):
			messages.success(request, "Usuario criado com sucesso")
		else:
			messages.error(request, "Usuario ja existente!")
	else:
		form = FormCadastro()

	return render(request, 'loja/login/cadastro.html', {'form': form})

def cad_produto(request):
	if request.method == 'POST':
		form = FormProduto(request.POST, request.FILES)

		if form.is_valid():
			produto = Produto()
			produto.nome = form.cleaned_data["nome"]
			produto.preco = form.cleaned_data["preco"]
			produto.descricao = form.cleaned_data["descricao"]
			produto.imagem = form.cleaned_data["imagem"]
			produto.em_Falta = form.cleaned_data["em_Falta"]
			produto.categoria = form.cleaned_data["categoria"]
			produto.save()

			messages.success(request, "Produto criado com sucesso ")
		else:
			messages.error(request, "Produto já existente!")
	else:
		form = FormProduto()

	return render(request, 'loja/cadastrar_produto.html', {'form': form})

def deleta_produto(request, id_nome):
	Produto.objects.filter(nome = id_nome).delete()
	return redirect(home)

def add_pedido(request, id_produto):
	if request.user.is_authenticated:
		if request.POST:
			usuario = request.user
			quantidade = int(request.POST.get('qtd_pedido'))
			produto = Produto.objects.get(nome = id_produto)

			pedido = None
			try:
				pedido = Pedido.objects.get(usuario = usuario.pk, estado_do_pedido = Pedido.ESTADO_PEDIDO[0][0])
			except ObjectDoesNotExist or Exception:
				pedido = Pedido(usuario = usuario)
				pedido.save()

			item = None
			try:
				item = Item.objects.get(id_pedido = pedido.pk, id_produto = id_produto, ativo = True)
				item.addQuantidade(quantidade)
				item.save()
			except ObjectDoesNotExist or Exception:
				item = Item(id_pedido = pedido, id_produto = produto, quantidade = quantidade)
				item.save()
			return redirect(pedidos_usuario)
	else:
		return redirect(login_page)


def produto_tipo(request, tipo):
	tipo_produtos = []
	if tipo == 'todos':
		tipo_produtos = Produto.objects.all()
	else:
		tipo_produtos = Produto.objects.filter(categoria = tipo)
	return render(request, 'loja/cardapio/tipo_produtos.html', {'produtos': tipo_produtos})

def sair(request):
	controller = ControllerUsuario()
	controller.sair(request)
	return redirect(home)


def pedidos_usuario(request):
	if not request.user.is_superuser:
		vazio = False
		usuario = request.user
		pedidos = Pedido.objects.filter(usuario = usuario.pk).order_by('-data_do_pedido')
		if len(pedidos) <= 0:
			vazio = True
		return render(request, 'loja/pedido/pedidos.html', {'pedidos' : pedidos, 'vazio' : vazio })
	return redirect(home)


def itens_pedido(request, id_pedido):
	vazio = False
	itens = Item.objects.filter(id_pedido = id_pedido)
	pedido = Pedido.objects.get(pk = id_pedido)
	state_pedido = pedido.estado_do_pedido
	usuario = Usuario.objects.get(username = pedido.usuario)

	if len(itens) <= 0:
		vazio = True
	return render(request, 'loja/pedido/itens_pedido.html',
		{'itens': itens,
		'id_pedido' : id_pedido,
		'status' : Pedido.ESTADO_PEDIDO,
		'state_pedido' : state_pedido,
		'vazio' : vazio,
		'usuario' : usuario.__str__,
		'endereco' : usuario.endereco,
		'cep' : usuario.cep })


def ver_comprovante(request, id_pedido):
	itens = Item.objects.filter(id_pedido = id_pedido)
	return render(request, 'loja/pedido/comprovante.html', {'itens': itens,'id_pedido':id_pedido})

def all_pedidos(request):
	if request.user.is_superuser:
		vazio = False
		pedidos = Pedido.objects.exclude(estado_do_pedido = Pedido.ESTADO_PEDIDO[0][0]).order_by('data_do_pedido')
		if len(pedidos) <= 0:
			vazio = True
		return render(request, 'loja/pedido/pedidos.html', {'pedidos' : pedidos, 'vazio' : vazio})
	return redirect(home)

def alter_status(request, id_pedido):
	if request.POST and request.user.is_superuser:
		status_key = request.POST.getlist('pedido_status')
		new_status = str(status_key[0])
		pedido = Pedido.objects.get(pk = id_pedido)
		pedido.estado_do_pedido = new_status
		pedido.save()
	return itens_pedido(request, id_pedido)

def concluir_pedido(request, id_pedido):
	pedido = Pedido.objects.get(pk = id_pedido)
	pedido.estado_do_pedido = Pedido.ESTADO_PEDIDO[1][0]
	pedido.save()
	return ver_comprovante(request,id_pedido)


def modificar_qtd_item(request, id_item, id_pedido):
	if request.POST:
		quantidade_nova = int(request.POST.get('qtd_item'))
		if quantidade_nova > 0:
			item = Item.objects.get(pk = id_item)
			item.quantidade = quantidade_nova
			item.save()
	return itens_pedido(request, id_pedido)

def cancelar_pedido(request, id_pedido):
	Item.objects.filter(id_pedido = id_pedido).delete()
	Pedido.objects.filter(pk = id_pedido).delete()
	return redirect(home)


def ver_pdf(request, id_pedido):
	pedido = Pedido.objects.get(id = id_pedido)
	usuario = Usuario.objects.get(username = pedido.usuario)
	itens =  Item.objects.filter(id_pedido = id_pedido)
	return write_to_pdf(request,'loja/pedido/template_comprovante.html',{'itens':itens,'usuario':usuario})

def buscar(request):
	vazio = False
	if request.POST:
		value_busca = str(request.POST.get('busca'))
		valores_busca = Produto.objects.filter(nome__icontains = value_busca)
		if len(valores_busca) <= 0:
			vazio = True
		return render(request, 'loja/cardapio/tipo_produtos.html', {'produtos': valores_busca, 'vazio' : vazio})
	return redirect(home)

def fazer_pedido(request):
	try:
		pedido = Pedido.objects.filter(
			usuario = request.user,
			estado_do_pedido = Pedido.ESTADO_PEDIDO[0][0])[0]
		return itens_pedido(request, pedido.pk)
	except IndexError:
		pedido = Pedido(usuario = request.user)
		pedido.save()
		return itens_pedido(request, pedido.pk)

def editar_perfil(request):
	if request.user.is_authenticated:
		usuario = Usuario.objects.get(username = request.user.username)
		if request.method == 'POST':
			form = FormCadastro(request.POST)
			controller = ControllerUsuario()
			if controller.editar_usuario(request, form):
				messages.success(request, "Informacões alteradas com sucesso")
			else:
				messages.error(request, "Erro ao editar informacões")
		else:
			form = FormCadastro()
		return render(request,'loja/editar_perfil.html',{'form':form,'usuario':usuario})

loja/templates/loja/bebida.html
{% extends 'loja/cardapio.html' %}
{% block list %}
{% load staticfiles %}


<div class="row distance">

{% for pro in produtos_bebida %}


  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <img alt="Hamburguer" title="Hamburguer" src="{{pro.imagem|cut:'loja'}}" height="171px" width="170px"/>
      <div class="caption ">
        <hr>
        <h4>{{pro.nome}}</h4>
        <hr>
        <p >R$ {{ pro.preco }}</p>
        <button type="button" class="btn btn-primary btn-mini" data-toggle="modal" data-target="#myModal">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </button>

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">{{pro.nome}}</h4>
              </div>
              <div class="modal-body">
                <h5 class="modal-title" id="myModalLabel">{{ pro.descricao }}</h5>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary">Salvar</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
</div>



{% endblock %}

loja/templates/loja/cadastrar_produto.html
{% extends 'loja/base.html' %}
{% load widget_tweaks %}
{% block content %}

<form action="{% url 'cadastrar_produto' %}" enctype="multipart/form-data"     class="form-horizontal col-md-offset-1 col-md-10 my_form" method="POST">
{% csrf_token %}

{% for mensagem in messages %}
     {% if mensagem.level == 40 %}
         <ul>
           <li>{{ mensagem }}</li>
         </ul>
     {% endif %}
     {% if mensagem.level == 25 %}
          <script type="text/javascript">
              alert("{{mensagem}}")
              window.location.href = "/cardapio/todos/"
          </script>
     {% endif %}
 {% endfor %}


   <div class="form-group has-feedback">
        <label class="control-label col-sm-2" for="id_nome">Nome:</label>

        <div class="col-sm-10">
            {% render_field form.nome class="form-control" placeholder="Digite o nome do produto " %}
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="id_preco">Preço:</label>

        <div class="col-sm-10">
            {% render_field form.preco class="form-control" placeholder=" Digite o preço do produto"  %}
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="id_descricao">Descrição:</label>

        <div class="col-sm-10">
             {% render_field form.descricao class="form-control" placeholder="Digite a descricao do produto "%}
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="id_imagem">Imagem:</label>

        <div class="col-sm-5">
             {% render_field form.imagem class="form-control" placeholder=""%}
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="id_imagem">Em Falta:</label>

        <div class="col-sm-2">
             {% render_field form.em_Falta class="form-control" placeholder=" "%}
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="id_imagem">Categoria:</label>

        <div class="col-sm-10">
             {% render_field form.categoria class="form-control" placeholder=" "%}
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Cadastrar</button>
        </div>
    </div>


</form>


{% endblock %}

loja/templates/loja/cardapio.html
{% extends 'loja/base.html' %}

{% block content %}
{% load staticfiles %}
{% load app_filters %}




<div class="row distance">


   <div class="btn-group btn-group-justified" role="group" aria-label="...">
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default"><a href="{% url 'todos' %}" class="btn basic_link"><b>Tudo</b></a></button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default"><a href="{% url 'hamburguer' %}" class="btn basic_link"><b>Hambúrguer</b></a></button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default"><a href="{% url 'pastel' %}" class="btn basic_link"><b>Pastel</b></a></button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default"><a href="{% url 'pizza' %}" class="btn basic_link"><b>Pizza</b></a></button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" class="btn btn-default"><a href="{% url 'bebida' %}" class="btn basic_link"><b>Bebida</b></a></button>
    </div>
  </div>
  <!--Conteudo -->
  {% block list %}

  {% endblock %}

</div>
{% endblock %}

loja/templates/loja/editar_perfil.html
{% extends 'loja/base.html' %}
{% load widget_tweaks %}
{% block content %}

<form action="{% url 'editar_perfil' %}" data-toggle="validator" role="form" class="form-horizontal col-md-offset-1 col-md-10 my_form" method="POST">{% csrf_token %}
   {% for mensagem in messages %}
        {% if mensagem.level == 40 %}
            <ul>
              <li>{{ mensagem }}</li>
            </ul>
        {% endif %}
        {% if mensagem.level == 25 %}
             <script type="text/javascript">
                 alert("{{mensagem}}")
                 window.location.href = "/entrar/"
             </script>
        {% endif %}
    {% endfor %}

    <div class="form-group has-feedback">
        <label class="control-label col-sm-2" for="id_nome">Nome:</label>
       
        <div class="col-sm-10">
            {% render_field form.nome class="form-control" value=usuario.first_name %}
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="id_username">Usuário:</label>
       
        <div class="col-sm-10">
            {% render_field form.username class="form-control" value=usuario.username disabled="disabled"%}

        </div>


    </div>
    
    <div class="form-group has-feedback">
        <label class="control-label col-sm-2" for="id_email">E-mail:</label>
        
        <div class="col-sm-10">
            {% render_field form.email class="form-control" value=usuario.email pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"%}
        </div>

        <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="id_telefone">Telefone:</label>
        
        <div class="col-sm-10">
             {% render_field form.telefone class="form-control" value=usuario.telefone pattern="\+{0,1}\({0,1}[0-9]{2,3}\){0,1}[0-9]{0,1}.{0,1}[0-9]{4}-{0,1}[0-9]{4}"%}
        </div> 
    </div>
    
    <div class="form-group">
        <label class="control-label col-sm-2" for="id_cpf">CPF:</label>
        
        <div class="col-sm-10">
             {% render_field form.cpf class="form-control" value=usuario.cpf pattern="[0-9]{3}.{0,1}[0-9]{3}.{0,1}[0-9]{3}-{0,1}[0-9]{2}"%}
        </div>
    </div>
    
    <div class="form-group">
        <label class="control-label col-sm-2" for="id_endereco">Endereço:</label>
        
        <div class="col-sm-10">
        {% render_field form.endereco class="form-control" value=usuario.endereco%}

        </div>
    </div>
    
    <div class="form-group">
        <label class="control-label col-sm-2" for="id_cep">CEP:</label>
          
        <div class="col-sm-10">
            {% render_field form.cep class="form-control" value=usuario.cep  pattern="[0-9]{5}-{0,1}[0-9]{3}"%}
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="id_senha">Senha:</label>
       
        <div class="col-sm-10">
             {% render_field form.senha class="form-control" %}
        </div>
    </div>
    
    <div class="form-group">
        <label class="control-label col-sm-2" for="id_csenha">Confirmar senha:</label>

        <div class="col-sm-10">
               {% render_field form.csenha class="form-control"%}
               
        </div>
    </div>


    <div class="form-group"> 
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Salvar alteracoes</button>
        </div>
    </div>
     

</form>


{% endblock %}

loja/templates/loja/hamburguer.html
{% extends 'loja/cardapio.html' %}
{% block list %}
{% load staticfiles %}


<div class="row distance">

{% for pro in produtos_hamburguer %}

  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <img alt="Hamburguer" title="Hamburguer" src="{{pro.imagem|cut:'loja'}}" height="171px" width="170px"/>
      <div class="caption ">
        <hr>
        <h4>{{ pro.nome }}</h4>
        <hr> 
        <p >R$ {{ pro.preco }}</p>
        <button type="button" class="btn btn-primary btn-mini" data-toggle="modal" data-target="#myModal">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </button>

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">{{pro.nome}}</h4>
              </div>
              <div class="modal-body">
                <h5 class="modal-title" id="myModalLabel">{{ pro.descricao }}</h5>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary">Salvar</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
</div>



{% endblock %}

loja/templates/loja/navbar-top.html
<head>
<style>
ul {
    list-style-type: none;
    margin: 0px;
    padding: 0px;
    overflow: hidden;
    background-color: #333333;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 16px;
    text-decoration: none;
}

li a:hover {
    background-color: #111111;
}
</style>
</head>
<body>

<ul>
  <li><a href="#home">Home</a></li>
  <li><a href="#news">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li><a href="#about">About</a></li>
</ul>

</body>